### ISSUE TITLE
Replace JDT @Nullable annotation with JSpecify

### ISSUE THREAD

**Issue by vorburger** [vorburger/ch.vorburger.exec#133]
I need to use this library in an environment where the JDT `@Nullable` annotation (AKA `org.eclipse.jdt:org.eclipse.jdt.annotation`) is not available, or could only be made available if I took on additional maintenance burden.

That environment recommends to use https://jspecify.dev for modern "Type-use" `null` annotations. I will therefore switch this project to that.

@cpovirk FYI

**Comment by cpovirk** [comment]
Thanks. I have a guess as to which environment that is... :)

There is currently a catch: We changed the package name for the JSpecify annotations in the open-source project, but we haven't yet updated our "environment" for the change. So you'd have to set up Copybara to rewrite the annotation's package name on the way in.

In fairness, at that point, you could perhaps more easily stick with Eclipse externally and have Copybara rewrite it to JSpecify internally: It would save you the step of changing the external code, and you'd need the rewriting either way. Plus, JSpecify is still at 0.3.0, and while I wouldn't expect any actual disruption for you at this point, it's not clear that it's worth your effort to go out of your way to take on even a small risk of disruption.

So I'd definitely encourage JSpecify where appropriate now, but you might put off changing the open-source project for the moment. @kevinb9n may have advice.

**Comment by vorburger** [comment]
> we haven't yet updated our "environment" for the change

Oh. That's good to know... thank you, for this heads-up!

In that case, I'm preparing a PR to switch this project later, and will instead just use good ol' (cough) JSR 305, for now.

Seems simpler and clearer than rewrite the annotation's package name on the way in. (I don't actually use "Type-use" annotations, in this project; this only uses `@Nullable` and I just want to be able to be able to build it the simplest way possible.)

**Comment by agentgt** [comment]
@vorburger and @cpovirk Aren't the JDT annotations mostly safe in terms of dependency because their retention is `CLASS`?

That is you can largely make the dependency an optional/provided one and in your modules (if you are modular) you do `requires static org.eclipse.jdt.annotation;` ?

That was my hesitation right now to adopt JSpecify for https://github.com/jstachio/jstachio is that I believe its retention is `RUNTIME` which means someone could reflectively access it and therefore you need it as a transitive dependency.

**Comment by cpovirk** [comment]
One of my missions in life is to discourage people from using `optional`/`provided` for annotation dependencies :) It can lead to [problems, even compile-time problems for `CLASS`-retention annotations](https://github.com/google/guava/wiki/UseGuavaInYourBuild#what-about-guavas-own-dependencies). (I wish that I knew more about modules and `requires static`, but my uneducated guess would be that that is safer.) Those problems aren't _common_, but I'd generally rather let people _opt in_ to having the problems when they choose to omit dependencies that would otherwise be included by default :)

Still, it's clear that `RUNTIME` is _at best equally safe_ to `CLASS`. And in practice, even though the JVM is supposed to ignore missing annotations at runtime (including during reflection), there have been bugs in that code in the past. There's no denying that `CLASS` retention makes any remaining bugs of that type irrelevant.

One minor feature of JSpecify is that the dependency is at least going to be a small one (like the JDT annotations)—and, if all goes well, the dependency that projects increasingly include anyway. So the hope is that users don't end up pulling in the jsr305 annotations _and_ the Checker Framework annotations _and_.... Then there ends up being one small jar that is easier to justify including. And if we end up achieving the goal of having one jar, enough of whose users need `RUNTIME` retention (e.g., for Guice), then it makes sense for it to use `RUNTIME` retention. (That said, we have considered offering a separate set of `CLASS`-retention annotations and/or standardizing a way for users to define their own. If you want `CLASS` retention nowadays, though, it's like that JDT is the simplest way to go _if_ you don't need the magic of JSpecify's `@NullMarked` for Kotlin purposes or other reasons.)

(On JSpecify use more generally: Thanks for following along jstachio pop up in my searches. I still need to see if we have a version of [our compatibility warning](https://github.com/jspecify/jspecify#jspecify) with a little more subtlety. I would expect in practice for you to be fine depending on it, but I have been wrong about such things before... :))
